--練習2 
-- 建立 DISTRICT_INF
 CREATE TABLE DISTRICT_INF(
 DISTRICT_SERIAL VARCHAR2(10) PRIMARY KEY,
 DISTRICT NVARCHAR2(10),
 OFFICE_ADDRESS NVARCHAR2(20),
 OFFICE_TEL VARCHAR2(20)
 )
COMMIT;

-- 建立 POLICE_INF
CREATE TABLE POLICE_INF(
POLICE_SERIAL VARCHAR2(10) PRIMARY KEY,
POLICE_NAME NVARCHAR2(10),
POLICE_ADDRESS NVARCHAR2(20),
POLICE_TEL VARCHAR2(20)
)
COMMIT;

-- 新增 DISTRICT_INF 資料
INSERT INTO DISTRICT_INF VALUES ('C001', '大埔里', '竹南鎮公義路1035號
', '037581072')
INSERT INTO DISTRICT_INF VALUES ('C002', '竹南里', '竹南鎮竹南里中山路103號
', '037472735')
INSERT INTO DISTRICT_INF VALUES ('C003', '山佳里', '竹南鎮山佳里國光街14號
', '037614186')
INSERT INTO DISTRICT_INF VALUES ('C004', '埔頂里', '後龍鎮埔頂里中興路136-1號
', '037724839')
INSERT INTO DISTRICT_INF VALUES ('C005', '緣苗里', '苗栗市綠苗里中正路766號
', '037333240')
INSERT INTO DISTRICT_INF VALUES ('C006', '民族里', '民族里民族路96號
', '037660001')
INSERT INTO DISTRICT_INF VALUES ('C007', '忠孝里', '忠孝里光大街82號', '037661145
')

-- 新增POLICE_INF 資料
INSERT INTO POLICE_INF VALUES ('M001', '竹南分局', '苗栗縣竹南鎮民族街72號
', '037474796')
INSERT INTO POLICE_INF VALUES ('M002', '苗栗分局', '苗栗縣苗栗市金鳳街109號
', '037320059')
INSERT INTO POLICE_INF VALUES ('M003', '頭份分局', '苗栗縣頭份市中興路503號
', '037663004')
COMMIT;

-- 新增 FACILITY_INF 資料
INSERT INTO FACILITY_INF VALUES ('公寓','C001','苗栗縣竹南鎮中埔街20號', 100, 1,'M001')
INSERT INTO FACILITY_INF VALUES ('大樓','C002','苗栗縣竹南鎮和平街79號', 3142, 1,'M001')
INSERT INTO FACILITY_INF VALUES ('大樓','C003','苗栗縣竹南鎮龍山路三段142號', 1072, 1,'M001')
INSERT INTO FACILITY_INF VALUES ('公共設施','C004','苗栗縣後龍鎮中華路1498號', 32, 1,'M001')
INSERT INTO FACILITY_INF VALUES ('公寓','C005','苗栗縣苗栗市米市街80號', 106, 1,'M002'),
INSERT INTO FACILITY_INF VALUES ('公寓','C005','苗栗縣苗栗市光復路117號', 26, 1,'M002'),
INSERT INTO FACILITY_INF VALUES ('大樓','C005','苗栗縣苗栗市博愛街109號', 2038, 2,'M002'),
INSERT INTO FACILITY_INF VALUES ('大樓','C005','苗栗縣苗栗市大同路53號', 128, 2,'M002'),
INSERT INTO FACILITY_INF VALUES ('公共設施','C006','苗栗縣頭份市民族里和平路102號', 353, 1,'M003'),
INSERT INTO FACILITY_INF VALUES ('私營單位','C007','苗栗縣頭份市忠孝忠孝一路69號', 501, 1,'M003'),
INSERT INTO FACILITY_INF VALUES ('公寓','C008','苗栗縣頭份市信義里中正路65號', 194, 1,'M003'),
INSERT INTO FACILITY_INF VALUES ('私營單位','C008','苗栗縣頭份市信義里中正路116號', 78, 1,'M003')

SELECT * FROM FACILITY_INF

DELETE FROM POLICE_INF WHERE POLICE_SERIAL = '公寓'
COMMIT;
COMMIT;
-- 練習4-1

SELECT DISTINCT PI.POLICE_NAME, PI.POLICE_TEL
FROM(
    SELECT PEOPLE, POLICE_SERIAL
    FROM FACILITY_INF
    WHERE PEOPLE > 1000) AA
LEFT JOIN POLICE_INF PI
ON AA.POLICE_SERIAL = PI.POLICE_SERIAL

-- 練習4-2

SELECT PI.POLICE_NAME, PI.POLICE_TEL, COUNT(POLICE_TEL) AS TOTAL
FROM(
    SELECT PEOPLE, POLICE_SERIAL, FACILITY_ADDRESS
    FROM FACILITY_INF
    WHERE PEOPLE > 1000) AA,
    POLICE_INF PI
WHERE AA.POLICE_SERIAL = PI.POLICE_SERIAL
GROUP BY PI.POLICE_NAME,PI.POLICE_TEL

-- 練習4-3
SELECT BB.POLICE_NAME, BB.POLICE_TEL, BB.FACILITY_ADDRESS, BB.TYPE, CC.TOTAL
FROM
    (SELECT PI.POLICE_NAME, PI.POLICE_TEL, AA.FACILITY_ADDRESS, AA.TYPE
        FROM(
        SELECT PEOPLE, POLICE_SERIAL, FACILITY_ADDRESS, TYPE
        FROM FACILITY_INF
        WHERE PEOPLE > 1000) AA
    LEFT JOIN POLICE_INF PI
    ON AA.POLICE_SERIAL = PI.POLICE_SERIAL)BB
LEFT JOIN 
    (SELECT PI.POLICE_NAME, PI.POLICE_TEL, COUNT(POLICE_TEL) AS TOTAL
    FROM(
        SELECT PEOPLE, POLICE_SERIAL, FACILITY_ADDRESS
        FROM FACILITY_INF
        WHERE PEOPLE > 1000) AA,
        POLICE_INF PI
    WHERE AA.POLICE_SERIAL = PI.POLICE_SERIAL
    GROUP BY PI.POLICE_NAME,PI.POLICE_TEL)CC
ON BB.POLICE_NAME = CC.POLICE_NAME

-- 練習4-4
SELECT BB.DISTRICT, BB.FACILITY_ADDRESS, BB.PEOPLE, PI.POLICE_NAME, PI.POLICE_TEL
FROM
    (SELECT DI.DISTRICT, AA.FACILITY_ADDRESS, AA.PEOPLE, AA.POLICE_SERIAL
    FROM 
        (SELECT DISTRICT_SERIAL, FACILITY_ADDRESS, PEOPLE, POLICE_SERIAL
        FROM FACILITY_INF 
        WHERE FACILITY_ADDRESS LIKE '%中%')AA
    LEFT JOIN DISTRICT_INF DI
    ON DI.DISTRICT_SERIAL = AA.DISTRICT_SERIAL)BB
LEFT JOIN POLICE_INF PI
ON PI.POLICE_SERIAL = BB.POLICE_SERIAL

-- 練習4-5
SELECT AA.TYPE, DI.DISTRICT, DI.OFFICE_ADDRESS, AA.FACILITY_ADDRESS, AA.PEOPLE
FROM
    (SELECT TYPE, DISTRICT_SERIAL, FACILITY_ADDRESS, PEOPLE
    FROM FACILITY_INF
    WHERE TYPE = '公寓' OR TYPE = '大樓')AA
LEFT JOIN DISTRICT_INF DI
ON AA.DISTRICT_SERIAL = DI.DISTRICT_SERIAL

-- 練習5-1
UPDATE FACILITY_INF 
SET PEOPLE = 5000
WHERE FACILITY_ADDRESS = '苗栗縣竹南鎮和平街79號'
COMMIT;

-- 練習5-2
DELETE FROM FACILITY_INF
WHERE PEOPLE < 1000
COMMIT;

